{
 "title": "Physical Resouces",
 "tags": [
  "ce359a7e935ca4002829d5f939cb2347c",
  "arms-prom",
  "k8s-resource"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{node!~\"master-.*\"})/sum(kube_node_status_capacity_cpu_cores{node!~\"master-.*\"})*100"
    }
   ]
  },
  {
   "title": "Amount of Pod",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(kube_pod_info{}) by (created_by_kind,namespace)",
     "legendFormat": "{{created_by_kind}}@{{namespace}}"
    },
    { "expr": "count(kube_pod_info{})", "legendFormat": "amount of pod" },
    {
     "expr": "count(kube_pod_info{}) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{node!~\"master-.*\"})/sum(kube_node_status_allocatable_memory_bytes{node!~\"master-.*\"})*100"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{node!~\"master-.*\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity_cpu_cores{node!~\"master-.*\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{node!~\"master-.*\"})/1024/1024/1024"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable_memory_bytes{node!~\"master-.*\"})/1024/1024/1024"
    }
   ]
  },
  {
   "title": "CPU Usage In Single Node",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{node!~\"master-.*\"}) by (node)/sum(kube_node_status_capacity_cpu_cores{node!~\"master-.*\"}) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Memory Usage In Single Node",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{node!~\"master-.*\"}) by (node) / sum(kube_node_status_allocatable_memory_bytes{node!~\"master-.*\"}) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Disk Usage In Node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1-(sum(node_filesystem_free_bytes{}) by(instance,device) / sum(node_filesystem_size_bytes{}) by(instance,device))",
     "legendFormat": "{{device}}@{{instance}}"
    }
   ]
  }
 ]
}