version: "3.1"
services:
  alertmanager:
    image: registry.cn-shenzhen.aliyuncs.com/haoyu36/alertmanager:v0.20.0
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    restart: always
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
