version: "3.3"
services:
  cadvisor:
    image: registry.cn-shenzhen.aliyuncs.com/haoyu36/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 8080:8080
    restart: always

  vmware:
    image: registry.cn-shenzhen.aliyuncs.com/haoyu36/vmware_exporter
    ports:
      - 9272:9272
    environment:
      VSPHERE_HOST: <HOST_IP> 
      VSPHERE_IGNORE_SSL: "True"
      VSPHERE_USER: <USER> 
      VSPHERE_PASSWORD: <PASSWORD>
    restart: always

  mysql:
    image: registry.cn-shenzhen.aliyuncs.com/haoyu36/mysqld-exporter
    environment:
      DATA_SOURCE_NAME: 'exporter:Admin123@(192.168.1.199:3306)/'
    ports:
      - 9104:9104
    restart: always

  redis:
    image: registry.cn-shenzhen.aliyuncs.com/haoyu36/redis_exporter
    environment:
      REDIS_ADDR: '127.0.0.1:6379'
      REDIS_USER: ''
      REDIS_PASSWORD: ''
    ports:
      - 9121:9121
    restart: always

  mongodb:
    image: registry.cn-shenzhen.aliyuncs.com/haoyu36/mongodb_exporter
    environment:
      MONGODB_URI: mongodb://<your mongodb ip>:27017
    ports:
      - 9216:9216
    restart: always

  elasticsearch:
    image: registry.cn-shenzhen.aliyuncs.com/haoyu36/elasticsearch_exporter
    command:
      - '--es.uri=http://elasticsearch:9200'
    ports:
      - 9114:9114
    restart: always