version: "3.1"
services:
  grafana:
    image: registry.cn-shenzhen.aliyuncs.com/haoyu36/grafana:6.6.0
    ports:
      - 3000:3000
    volumes:
      - ./grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring
    restart: always
