version: "3.3"
services:
  influxdb:
    image: influxdb:1.8.0
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    environment:
      - INFLUXDB_DB=prometheus
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    volumes:
      - ./data:/var/lib/influxdb
      - ./influxdb.conf:/etc/influxdb/influxdb.conf
