global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'DingDing'

templates:
- 'dingding.tmpl'

receivers:
- name: 'DingDing'
  webhook_configs:
  - url: 'http://192.168.5.214:8060/dingtalk/webhook1/send'
    send_resolved: true

    
