version: "3.3"
services:
  prometheus:
    image: registry.cn-shenzhen.aliyuncs.com/haoyu36/locust_exporter:v0.3.0
    environment:
      LOCUST_EXPORTER_URI: http://192.168.1.133:8089
    ports:
      - 9646:9646
    restart: always

